# Generated by Django 5.0.3 on 2024-04-02 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empregados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", models.CharField(blank=True, max_length=15, null=True)),
                ("nome", models.CharField(blank=True, max_length=200, null=True)),
                ("data_admissao", models.DateTimeField()),
                ("cargo", models.CharField(max_length=150)),
            ],
        ),
    ]
